version: "3.9"

services:
  db:
    image: postgres:13
    container_name: biofit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: biofit
      POSTGRES_PASSWORD: biofitpass
      POSTGRES_DB: biofitdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d # For initial SQL scripts
      - ./db/init/feedback_sleep.csv:/feedback_sleep.csv
    ports:
      - "5432:5432"

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: biofit-streamlit
    depends_on:
      - db
      - data
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://biofit:biofitpass@db:5432/biofitdb
      DATA_SERVICE_URL: http://data:8001/fetch
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"

  data:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    container_name: biofit-data
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://biofit:biofitpass@db:5432/biofitdb
    ports:
      - "8000:8000"

  streamlit-feedback:
    build:
      context: ./streamlit_app
    command: streamlit run streamlit_feedback.py --server.port 8502
    container_name: biofit-streamlit-feedback
    depends_on:
      - feedback-api
    restart: unless-stopped
    environment:
      - FEEDBACK_API_URL=http://feedback-api:8001/feedback
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8502:8502"

  feedback-api:
    build:
      context: ./feedback_api
    container_name: feedback-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://biofit:biofitpass@db:5432/biofitdb
    ports:
      - "8001:8001"

  ai_service:
    build: 
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: biofit-ai-service
    depends_on:
      - db
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://biofit:biofitpass@db:5432/biofitdb
      MODEL_PATH: /app/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
      WINDOW: 7

    volumes:
      - ./ai_service:/app

    ports:
      - "8002:8002"


volumes:
  pgdata:
